version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db
  kuberfriend-app:
    build:
      context: ../kuberfriend-app
      dockerfile: ./Dockerfile
    image: kuberfriend-app:tag
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  kuberfriend-processor:
    build:
      context: ../kuberfriend-processor
      dockerfile: ./Dockerfile
    image: kuberfriend-processor:tag
    ports:
      - "8082:8082"
    depends_on:
      - mongo
volumes:
  mongo_volume: