apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: kuberfriend-processor
  name: kuberfriend-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kuberfriend-processor
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: kuberfriend-processor
    spec:
      containers:
      - image: kuberfriend-processor:tag
        imagePullPolicy: ""
        name: kuberfriend-processor
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
